#!/bin/bash
if [ -f /usr/bin/curl ] || [ -f /data/data/com.termux/files/usr/bin/curl ];then
   function banner {
      printf " __ __  _____ _____  \n" | lolcat
      printf "|  T  T/ ___// ___/  \n" | lolcat
      printf "|  |  (   \_(   \_   \n" | lolcat
      printf "l_   _j\__  T\__  T  \n" | lolcat
      printf "|     |/  \ |/  \ |  \n" | lolcat
      printf "|  |  |\    |\    |  \n" | lolcat
      printf "|__j__| \___j \___j  \n" | lolcat
      printf "A Simply XSS Scanner \n" | lolcat
      printf "|-------------------| \n" | lolcat
      printf "|     CODED BY:     | \n" | lolcat
      printf "|       G3K45       | \n" | lolcat
      printf "|___________________| \n" | lolcat
   }
  
   function exbanner {
     printf "..######....#######...#######..########..########..##....##.######## \n" | lolcat
     printf ".##....##..##.....##.##.....##.##.....##.##.....##..##..##..##...... \n" | lolcat
     printf ".##........##.....##.##.....##.##.....##.##.....##...####...##...... \n" | lolcat
     printf ".##...####.##.....##.##.....##.##.....##.########.....##....######.. \n" | lolcat
     printf ".##....##..##.....##.##.....##.##.....##.##.....##....##....##...... \n" | lolcat
     printf ".##....##..##.....##.##.....##.##.....##.##.....##....##....##...... \n" | lolcat
     printf "..######....#######...#######..########..########.....##....######## \n" | lolcat
   }
   function exitsys {
      printf "Do you want to exit the program? \n"
      printf "[1]yes [2]no:"
      read option
      if [[ $option == 1 ]];then
         exbanner;
      else
         main
      fi
   }

   function main {
      clear
      banner;
      printf "Enter IP or URL:"
      read ipu
      resp=$(curl -I $ipu)
      keyword="HTTP/1.1 200 OK"
      s_keyword="HTTP/2 200"
      filename="XSS.txt"
      x=0
      if [[ $resp =~ $keyword ]] || [[ $resp =~ $s_keyword ]];then
         while read -r line;do
            response=$(curl -X POST -d " $line" $ipu)
            if [[ $response =~ $line ]];then
                printf "Vulnerability found \n" | lolcat
                break
            else
                printf "Vulnerability not found" | lolcat
                continue
            fi
         done < "$filename"
      else
         printf "Error \n"
      fi
      exitsys;
   }
   main;
else
   printf "Please run the installer \n";
fi
